### ISSUE TITLE
Spoiler logs should be collated into a single file

### ISSUE THREAD

**Issue by glasnonck** [LaneDibello/Kotor-Randomizer-2#18]
Enhancement. Instead of using separate CSV files, the spoiler logs could be more nicely presented in a single XML or ODS file with multiple sheets.

**Comment by LaneDibello** [comment]
Would this really be an improvement? I feel like having one file that is continuously growing in size as the user views spoilers would rapidly get cluttered, especially if the user does frequent rando runs. Separate files are more manageable IMO. 
Though I may be misunderstanding the goal of this enhancement.

**Comment by glasnonck** [comment]
I may not have described it well enough.The enhancement is to collate the files created at the same time together, not to continue to add to a single spoiler log each time you generate it.

Right now Generating Spoiler Logs creates one file for each type of randomization that is both enabled and can generate its log. Instead of creating multiple files within a single log generation, I’d like to generate one file that contains all of the spoiler logs as separate tabs. The next time we generate spoiler logs, a new file with multiple tabs would be created.

**Comment by glasnonck** [comment]
I have a good lead on a way to do this effectively. I found a nuget package released under the MIT license that makes it easy to generate spreadsheets in excel format (https://github.com/ClosedXML/ClosedXML). I'm currently working on a branch to finish off both this issue and issue #7. I just need to figure out a good way to display Text randomization information...
