### ISSUE TITLE
Add a loading zone for the unused vulkar spice lab

### ISSUE THREAD

**Issue by glasnonck** [LaneDibello/Kotor-Randomizer-2#5]
### Summary
One module in the game files is not used in the final game and is thus inaccessible: the Vulkar Spice Lab. If this module is included in the randomization, another module will be completely inaccessible. It would be nice to add a way to reach this module from the Vulkar Base to allow it to be randomized without potentially causing problems if an important module can't be reached.

**Comment by LaneDibello** [comment]
We need to decide a location to put this load zone. The easiest way to add a load zone is to modify an existing door. ONe option that comes to mind is the elevator in the middle of the base that was converted into a storage closet (where the load zone was originally intended to be).

Though it is also possible to add a new door, add a trigger, or even put a script in a conversation that transitions to this location. 

We should definitely poll for interest.
