### ISSUE TITLE
Optionally output a spoiler log, both for qol and debug purposes.

### ISSUE THREAD

**Issue by LaneDibello** [LaneDibello/Kotor-Randomizer-2#7]
This will help with post-run retrospection, as well as with debugging the issues with module logic, and more.

May include:
- The seed
- Which module was replaced with what
- Table of item equivalents (may be slightly unreasonable)
- Maybe the other randomization changes

**Comment by glasnonck** [comment]
The seed and all active settings might be enough for some of the rando categories (items), for lack of a good way to display that information. And it might be the only good way to debug texture randomization.

**Comment by glasnonck** [comment]
I currently have spoiler logs for Models, Modules, and Items working. I'm saving them to separate CSV files upon request after randomization, but that makes it a bit difficult to manage. I might shift to using a spreadsheet format that can handle multiple worksheets.

**Comment by glasnonck** [comment]
- [ ] Seed
- [ ] Module replacements
- [ ] Item replacements
- [ ] Model replacements
- [ ] Music / Sound replacements
- [ ] 2DA replacements (maybe)
- [ ] Other replacements (Polymorph, NPC Pazaak, Party)

**Comment by LaneDibello** [comment]
Currently if you generate a spoiler log after randomizing content that is not included in logs, the program will happily report "Spoil logs created." when in fact not such file is created. (i.e. randomize only swoop race -> select generate spoilers).

This oversight may be less significant once spoiler logs exist for all content.
